### ISSUE TITLE
MaxCube reset to fatory defaults

### ISSUE THREAD

**Issue by dingusdk** [hackercowboy/python-maxcube-api#12]
My Maxcube is loosing the configuration (reset to factory defaults) with and interval of about 3-6 weeks. It only happens when connected to HA. Other users are having the same issue:

https://community.home-assistant.io/t/maxcube-loosing-configuration/46663

It looks like a general problem with MaxCube and not just your maxcube-api. Openhab users have had the same problem. I have tried changing the polling interval from 1 minute to 5 minutes as suggested by other users:

https://github.com/home-assistant/home-assistant/issues/12551#issuecomment-372113261

- and have not had the issue since (only about 14 days siince i did it, so not sure if it will actually fix it). 
It would be nice to be able to set this from the HA config, so i don't have to manually change the code each time HA is updated.

Another improvement (this was also done in openhab), was to be able to choose exclusive mode, so the maxcube-api does not close the connection.

**Comment by Ener-G** [comment]
> It would be nice to be able to set this from the HA config, so i don't have to manually change the code each time HA is updated.
> 
> Another improvement (this was also done in openhab), was to be able to choose exclusive mode, so the maxcube-api does not close the connection.

Yes, this would be an excellent solution

**Comment by cs42** [comment]
I had this problem (using FHEM FYI) too and was searching a cause for a long time. Reading many discussions I am sure now, that this is a connection handling problem of the max cube (some race condition/overflow). 

The solution seems to be to use a "blocking" access (open connection once, never close it) instead of opening a new connection on every query from a home automation system, if that is possible. As there can only be one connection to the cube at a time you can't use EQ-3 cloud then or connecting with their windows software.

As EQ-3 never officially documented their protocol I'm almost sure that they see this as "non issue"...

**Comment by dingusdk** [comment]
Making a longer polling interval only postponed the problem.
After a longer testing period of now about half a year, I am almost 100% sure the library should have a "exclusive" - keeping the connection mode, to solve the Max Cube resets.

**Comment by davidhrbaty** [comment]
Hello, 

Is there something new about this issue? I have the same problem with my setup ( home assistant and max cube ). I have pooling interval setup to 5 minutes and once about half a year max cube gateway is reset to factory settings.

**Comment by mike-k68** [comment]
Hello,
The only solution is to use a keep-alive connection:
Connect to the cube and never release the connection.

Doing so, i am able to poll every second without any factory reset.
But I need to kill my deamon whenever I want to use the Max! Software and restart it when I’m done. (The cube only allows one connection at a time)

If interested I can post my code in a fork here, but you may need to make adaptations, since I’ve taylored my code for my own need with my MQTT daemon.

**Comment by mvzut** [comment]
Hi mike-k68,

It would be great if you can share how you managed to change to a keep-alive connection! This would not only solve the issue of Cubes being reset, but would also enable us to have real-time updates. Using it as an MQTT daemon is also a really nice solution. Really interested!

**Comment by mike-k68** [comment]
Hi there,
What is the best way to send you my code ? (email).
I don’t want to create a fork and maintain it. Also I’m a python-newbie so my code is definitely not neat and taylored for my own need.
But it’s ok if you guys use it, modifiy and share it.

Regards
Mike

**Comment by unaiur** [comment]
The best way is forking this repository and upload your changes there. You
don’t need to maintain it. Just dump your code to GitHub

**Comment by mike-k68** [comment]
Ok, I did the fork.
You may find my code here: https://github.com/mike-k68/python-maxcube-api
Don't hesitate to ask questions if needed.

**Comment by unaiur** [comment]
Thank you. I have seen several improvements that are really good, like
reporting failed commands (current code does not validate the status code
in the response) or support for vacation mode.

**Comment by unaiur** [comment]
Resolved in 0.4.0 version
